apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - args:
        - --init-file
        - /data/application/database.sql
        env:
        - name: MYSQL_DATABASE
          value: Agenda
        - name: MYSQL_PASSWORD
          value: xcOP37L3
        - name: MYSQL_ROOT_PASSWORD
          value: xcOP37L3
        - name: MYSQL_USER
          value: admin
        image: mysql:latest
        imagePullPolicy: ""
        name: appbd
        ports:
        - containerPort: 0
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: basedatos
        - mountPath: /data/application/database.sql
          name: db-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: basedatos
        persistentVolumeClaim:
          claimName: basedatos
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
status: {}
