# Use una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /html

# Copia el script Python al directorio de trabajo en el contenedor
COPY ./html /html

# Instala las dependencias del script Python (si las hay)
RUN pip install holidays

# Comando que se ejecutará al iniciar el contenedor
CMD ["python", "/html/festivos.py"]

